dist: xenial
sudo: true
language: generic

before_install:
  - sudo add-apt-repository -y ppa:kelleyk/emacs
  - sudo apt-get update 
  - sudo apt-get install -y emacs26
  - sudo apt-get install -y graphviz plantuml ditaa

script:
  - emacs26 -batch -l foo.el
